queue:
  durable: true
  auto_delete: false
  exclusive: true
  no_wait: false
channel:
  auto_ack: true
  exclusive: false
  no_local: false
  no_wait: false
publish:
  mandatory: false
  immediate: false
exchange:
  type: "fanout"
  durable: true
  auto_delete: false
  enternal: true
  no_wait: false